 <!--

	GCaptcha - by Gabriel Silva
	Version 0.1alpha
	http://gabrielsilva.tk/gcaptcha

	This is an open source software
	Please read documentation before using it!!!

	- (Do not edit this file) -

-->

<html><head><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><meta name="robots" content="noindex,nofollow"><script src="html2canvas.min.js"></script><script type="text/javascript">document.addEventListener('contextmenu', event => event.preventDefault());</script><link rel="stylesheet" href="style.css"><style>*{-webkit-user-select:none;-webkit-touch-callout: none;}::-webkit-scrollbar{display: none;width: 0 !important;}body{overflow: hidden;margin: 0px;border: 0px;padding: 0px;}</style></head><body><div id="gcaptcha-loader"><img src="loading.gif"></div><div id="gcaptcha-container"><?php include 'gcaptcha.php'; echo '<span id="gcaptcha-stretch">'; setAndShowCaptcha(); echo '</span>';?><br><span id="gcaptcha-url">GCaptcha</span></div><a href="http://gabrielsilva.tk/gcaptcha" target="_blank" title="Powered by GCaptcha"><div id="gcaptcha-result" style="display: none;"></div></a><script type="text/javascript">const el = document.querySelector('#gcaptcha-container');html2canvas(el,{onrendered: function (canvas) {document.getElementById("gcaptcha-container").style.display = 'none';document.getElementById("gcaptcha-loader").style.display = 'none';document.getElementById("gcaptcha-result").style.display = 'inline-block';document.getElementById("gcaptcha-result").appendChild(canvas);setFrameSize();},useCORS: true})</script><script type="text/javascript">function reloadCaptcha(){var container = parent.document.getElementById('captcha');container.style.width = 30; container.style.height = 30; window.location.reload(true);} function setFrameSize(){var container = parent.document.getElementById('captcha');var result = document.getElementById('gcaptcha-result');container.style.width = result.offsetWidth;container.style.height = result.offsetHeight;}</script></body></html>